### ISSUE TITLE
Issue about multi-level routing

### ISSUE THREAD

**Issue by guanlei1996** [apohl79/audiogridder#143]
### Network topology
![网络拓扑](https://user-images.githubusercontent.com/19180533/93098546-923c8f80-f6d9-11ea-9f8e-d872db2e53cb.png)
I have set up a static routing table for the child router network segment on my main router.

### The server log
![截屏2020-09-14 下午10 24 59](https://user-images.githubusercontent.com/19180533/93098959-0bd47d80-f6da-11ea-9aff-1ce93140ebfe.png)

### The client log
![截屏2020-09-14 下午10 23 22](https://user-images.githubusercontent.com/19180533/93099005-1727a900-f6da-11ea-9593-aef0c916da01.png)

##### Work PC to AGridder server
![截屏2020-09-14 下午10 35 52](https://user-images.githubusercontent.com/19180533/93099658-da0fe680-f6da-11ea-92d3-b3cc2ac08a81.png)
##### AGridder to Work PC
![截屏2020-09-14 下午10 36 42](https://user-images.githubusercontent.com/19180533/93099665-dd0ad700-f6da-11ea-9333-10cb256d0ddb.png)

### Issue
Cannot use the work PC to connect to the AGridder server.

**Comment by guanlei1996** [comment]
I think the reason for the failure to connect is that the client's IP is incorrectly broadcast. Through the log of the AGridder server, you can see that you have been trying to connect to the port of the main router (192.168.3.1), which is impossible to connect successfully.

**Comment by apohl79** [comment]
The server is assuming a client to be on the same network or at least directly connectable by its incoming client IP. I guess your master router is NATing the connection from your workpc machine into the AG server network, which is why AG server sees the router IP?

The problem is, AG server connects back to the client right now, which was not the best idea... This will be changed in the future. For now, if your router supports it, you could forward AG client points from the router directly to your workpc. These ports would be 55055+ (depending on your sessions sizes you might have to forward a whole lot of ports). See #136 for a few more infos on what AG does.

**Comment by guanlei1996** [comment]
Alright. Thank you, bro.

**Comment by juanriccio** [comment]
Is there any actual need for broadcasting? If the client side knows the server's address, we should be good. Broadcast packets gave me a hard time when a friend came in with his own laptop. I had to flat out disable the firewall on his machine (freshly installed client) to be able to connect at all. The issue is the same @apohl79 mentioned above: https://github.com/apohl79/audiogridder/issues/136

**Comment by guanlei1996** [comment]
Why use broadcast? I think the TCP connection created by the client can be used. Because broadcasting is difficult to adapt to some complex network environments.
