### ISSUE TITLE
Release 1.1-Beta6: save in Logic takes a looong time.

### ISSUE THREAD

**Issue by ghost** [apohl79/audiogridder#155]
In Release 1.1-Beta6, when I try and hit save in Logic, it takes about 20-30 seconds before I can save. When I shut down the server the save procedure is as usual. Otherwise I LOVE the cpu-meter.

**Comment by apohl79** [comment]
Thx for the feedback! 

The save / shutdown behavior leaves room for improvement, agreed. There are a view threads, that are not coming down as fast as they could.

**Comment by Pete3030** [comment]
also saving in logic with higher buffer sizes (1024) somehow destroys my aggregate device (stuttering), can be solved by turning off and on of one my interfaces (2 x apogee ensemble).. when i deactivate the audiogridder plugins in logic, saving works as expected again.. btw. changing the buffer size in audiogridder has no effect on this behavior.

**Comment by Pete3030** [comment]
with beta7 it didn't really get better, still ongoing stuttering when saving in Logic, can be healed by deactivating some of running the AG plugins..

**Comment by apohl79** [comment]
From what version on did you see this issue?

**Comment by Pete3030** [comment]
Thats a little hard to say, since my current logic project evolved in the last weeks which might had an impact on cpu consumption/overall performance, but definitely in the betas 4-7, i think..
my overall feeling is that the AG plugins have somehow a greater impact on the overall audio performance in logic then the cpu consumption meter might let you think, if you know what i mean..
