### ISSUE TITLE
beta 8 freezing cubase

### ISSUE THREAD

**Issue by norburybrook** [apohl79/audiogridder#172]
installed beta 8 today and it's not workable here. Seems to freeze cubase requiring a force quit. Took a while to open my test song with audio gridders, it wouldn't open for the first 4 goes . I opened up a blank project and added a few griders then the project opened. 

Just seemed to cause Cubase to hang all the time, sometimes it would come back but mostly had to force quit.

M

**Comment by apohl79** [comment]
Beta7 works I guess?

**Comment by igbro** [comment]
Hi Andreas, Beta8 hangs Cubase too after a few minutes tweaking 2 different projects.
Cubase hangs (force to kill) while attempting to open an AG vst 2.0 FX (the wrapper not the wrapped)
Worked several times before.
Server was ok the 1st time and UI display task on server crashed the 2nd time.
Here are the logs and traces.

[FXplug 1.zip](https://github.com/apohl79/audiogridder/files/5362040/FXplug.1.zip)
[FXplug 2.zip](https://github.com/apohl79/audiogridder/files/5362041/FXplug.2.zip)
[Server 1.zip](https://github.com/apohl79/audiogridder/files/5362042/Server.1.zip)
[Server 2.zip](https://github.com/apohl79/audiogridder/files/5362044/Server.2.zip)

Cheers.

Igor.

**Comment by apohl79** [comment]
> Hi Andreas, Beta8 hangs Cubase too after a few minutes tweaking 2 different projects.
> Cubase hangs (force to kill) while attempting to open an AG vst 2.0 FX (the wrapper not the wrapped)
> Worked several times before.
> Server was ok the 1st time and UI display task on server crashed the 2nd time.
> Here are the logs and traces.
> 
> [FXplug 1.zip](https://github.com/apohl79/audiogridder/files/5362040/FXplug.1.zip)
> [FXplug 2.zip](https://github.com/apohl79/audiogridder/files/5362041/FXplug.2.zip)
> [Server 1.zip](https://github.com/apohl79/audiogridder/files/5362042/Server.1.zip)
> [Server 2.zip](https://github.com/apohl79/audiogridder/files/5362044/Server.2.zip)
> 
> Cheers.
> 
> Igor.

Thx, not sure if you were in windows or osx.

Can you enable tracing in the plugin with beta8 - you did on the server side? 

On windows, can you create a dump file from the task manager before killing cubase?

On osx, can you create a spindump via activity monitor before killing cubase?

**Comment by igbro** [comment]
I'm testing AG since alpha and we already discussed on several issues.

Win7 on both server and client, Cubase Pro 10.5.2

The only version I can work with and dare using it in professional projects is beta4.
It's working with few sparse glitches in audio but usable with a big block count (latency).
It never crashes server nor plugin even after 8 hours work.
My sound card is always set to 1024, witch is a short latency since this is an RME and an internal board.

Trace is on in beta8 server and you've got the trace files in the archives. 

As always, I can't make dump file from the server task because of a "denied access message". 
Do you mean a Cubase Dump? Must be huge! (would you be able to read this?)

**Comment by apohl79** [comment]
Got it.

> The only version I can work with and dare using it in professional projects is beta4.
> It's working with few sparse glitches in audio but usable with a big block count (latency).
> It never crashes server nor plugin even after 8 hours work.
> 
Yeah. Still trying to understand what is causing this… but at least there is a good version in the history.

> Trace is on in beta8 server and you've got the trace files in the archives.
> 

The plugin supports tracing too. It can be enabled via settings menu or config file, if you do not get it running, because it hangs directly at load time.

> As always, I can't make dump file from the server task because of a "denied access message".
> 
Ah I remember. I guess the account you use has no admin privileges?
> Do you mean a Cubase Dump? Must be huge! (would you be able to read this?)
> 
Yes a cubase dump. It will be huge. When you compress it, you can upload it using wetransfer hopefully. If that doesn’t work, let me know. 

But I guess you might not be allowed to do that either.

**Comment by norburybrook** [comment]
Beta 4 was good for me too. Windows 10 both sides. Cubase 10.5.x  M Sent from Mail for Windows 10 From: igbroSent: 12 October 2020 14:12To: apohl79/audiogridderCc: norburybrook; AuthorSubject: Re: [apohl79/audiogridder] beta 8 freezing cubase (#172) I'm testing AG since alpha and we already discussed on several issues.Win7 on both server and client, Cubase Pro 10.5.2The only version I can work with and dare using it in professional projects is beta4.It's working with few sparse glitches in audio but usable with a big block count (latency).It never crashes server nor plugin even after 8 hours work.My sound card is always set to 1024, witch is a short latency since this is an RME and an internal board.Trace is on in beta8 server and you've got the trace files in the archives.As always, I can't make dump file from the server task because of a "denied access message".Do you mean a Cubase Dump? Must be huge! (would you be able to read this?)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by igbro** [comment]
Thanks

>The plugin supports tracing too. It can be enabled via settings menu or config file, if you do not get it running, because it hangs directly at load time.

Ok will try this, thought it was only for server.

>Ah I remember. I guess the account you use has no admin privileges?

My server and client accounts are admin, but I'm getting to the server thru MS Remote desktop or VNC... maybe those must be launched as admin form the client too?
Locally at the client side, I think I will be able to dump Cubase. Never tried... (Cubase is always launched as admin)

What is your mail address for a possible wetransfer?

**Comment by apohl79** [comment]
You can use wetransfer at e47.org <http://e47.org/>. Thx for helping debug these issues!

**Comment by igbro** [comment]
So...

Activating trace in plugins (already activated in server), apparently prevents Cubase from freezing but its gives an alert and creates a crashdump (in the same file) each time I try to open an AG Vst2 wrapper instance, after a few normal attempts.

Same project as before witch hung Cubase doing the same thing with trace on server only.

I still not able to generate a global Cubase dump because of the access thing. Weird, because I'm admin on both side and the client (Cubase) is accessed locally !!!!

Here are those files.

[Cubase 10.5 crash dump.zip](https://github.com/apohl79/audiogridder/files/5365778/Cubase.10.5.crash.dump.zip)
[AudioGridderServer.zip](https://github.com/apohl79/audiogridder/files/5365780/AudioGridderServer.zip)
[AudioGridderFX.zip](https://github.com/apohl79/audiogridder/files/5365782/AudioGridderFX.zip)

Hope it helps.

**Comment by apohl79** [comment]
Thanks!
