### ISSUE TITLE
Beta 8 stil CPU spikes in Logic (unusable since beta 4)

### ISSUE THREAD

**Issue by simon1176f** [apohl79/audiogridder#194]
Hey, I cant use aGridder at all for any of my existing projects since Beta 4 - which is completely stable, I'm able to use 20+ instances of AGridder at 128 buffer with basically zero cpu usage in Logic. Now Beta 6,7,8 cause 4 of my 12 cores on my host computer to completely max out before even hitting play. This hasn't been an issue in all the revisions I've used, also the Alphas. I wouldn't know but is it maybe the cpu usage indicator thing in the plugin causing this? It has been having the CPU spike problem since that was implemented, could you do an option to not have that to see if it's the problem?

Kind Regards,
Simon

**Comment by timbit2006** [comment]
I've been experiencing and wondering the same thing.

**Comment by igbro** [comment]
Beta 4 is the only way to go for the moment for me too.

W7 on both sides and Cubase pro 10.5.2

The important thing is to keep trying other betas and give Andreas feedback with logs to help him improve the thing.

It's a huge challenge since Hardware/Software configurations can be so different!
Mac, PC, Hybrid Mac/PC, Cubase, LPX, S1, Reaper, FL, DP, Daw running on PC or MAC, Vst2, Vst3, AU plugin format...

**Comment by simon1176f** [comment]
Good advice!! Yes I do keep trying them as they're being released. And can't begin to show how grateful we all are for this thing!

**Comment by CaBuffalo** [comment]
@simon1176f  It looks like you have experience on Beta 4. I'm wondering if you can save the plugin setting whenever you diable the plugin and renable it, or ... the server crashed.

What I found is that all of the setting of the plugin are reset once that happened.

Thanks.
