### ISSUE TITLE
Request: Several plugin windows on server screen

### ISSUE THREAD

**Issue by juanriccio** [apohl79/audiogridder#201]
At the moment, I'm trying to make the best of Audiogridder by not transporting the UI to the plugin computer. I use Remote Desktop, so I have the server computer screen fully available.

I understand the Audiogridder server can only transmit one UI at a time, but how about showing them all on the local (master) screen? The UI to be transmitted can be chosen with the same criterion as it is now (the last one the plugin asked to edit), but in the meantime it would be great to have them all available for those of us who prefer to edit directly on the server.

**Comment by Clintcinnati** [comment]
I manage to do what you are asking to do by having multiple server instances on the plugin computer and giving each server instance a different Server ID- in my case I run six instances and number them 1 through 6.  I also have the servers set to all open at login, and I have screen capturing mode disabled.  Both my DAW computer and plug server are late 2012 Imacs connected via an ethernet wire set for dhcp with manual address.

The daw’s plugins list servers (name od server):1-6 and I have to make sure each plugin instance uses a unique server ID.

I keep both macs on my mix table and run heavy plugs like Scheps Omni channel and Butch Vig Vocals and other plugs that were not refreshing the gui on my DAW computer at a rate that was useable; turning knobs was a slide-show.

With the above mentioned setup, the plugin gui on the server respond as smoothly as if they were actually hardware, when I “turn a knob” it turns!
Same with meters and moving spectrum displays.  Also the plugin parameters are saved when I quit and re-open the session.

The only pain is having to assign the 1-6 server IDs each time I start working and fire up the server mac.  But it’s still way less bad than having to hide the editor and other windows just to get a knob to move or to see if my side chain for the bass is responding when using all the plugs on my DAW mac alone.

When running like this ( no screen capture, use a second mouse/screen/keyboard dedicated to served plugins) It’s truly amazing how perfectly it works.
With no screen capture, things work way more smoothy, once you realize you need to be using the other mouse to manipulate served plugs.

I hope in future releases, the Server ID for each server will be retained between startups, but such a minor problem, and otherwise stable and the latency is no problem.  I’m using Mixbus 32-c and sometimes Reaper.

**Comment by CrossGridder** [comment]
Use CrossGridder, all issues outlined in the original post and in the answer are solved by adopting my solution. Check my repository.
