### ISSUE TITLE
Host DAW hang on disconnect

### ISSUE THREAD

**Issue by smadgerano** [apohl79/audiogridder#217]
1.1 (BETA8), Cubase 10.5 Pro, Win 10 2004

When the server has a disconnection or restart for any reason, the client plugin locks up and hangs the host DAW. Some sort of graceful disconnect would be beneficial.

**Comment by jaacMusic** [comment]
Yes, it also happens to me on Cakewalk.

**Comment by CaBuffalo** [comment]
What's your server machine OS?

**Comment by jaacMusic** [comment]
For me my server is a Windows 10 system with nothing but AG server and plugins installed.

**Comment by CaBuffalo** [comment]
I have the server installed on Windows 7 / 10, I'm using Logic on MAC. I don't have the lock up issue anymore. I tried it on S1 before and it happened occasionally. The only lock up issues I have is that the server restarts if I tried to load any vst / vst3 which shows "Can't load this plugin" message in my DAW. But the server restarts itself instead of locking up.

I do notice that same plugin work sometimes, doesn't another time. I don't know if you guys have similar issue.
