### ISSUE TITLE
v9 for the president:)

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#228]
Testing new release and pure happiness so far!! All super fast and stable:) Big hugs to Andreas! Donating this week.

**Comment by CaBuffalo** [comment]
I have been torturing it in the past couple of hours. The GUI of Plugins in MAC OSX has been improved dramatically. This is the first thing I noticed. NICE !! Also, it's nice to ask you to confirm to close the plugin and there is more detailed error message if loading the plugin is failed.

I do have two incidents of locking up which caused the server to retart itself. I don't have the detail of the locking up yet. But it's nice to see the server restarted itself when the locking up happened so I can have the work continued.

Will give more feedback down the road.

Thanks, Andreas.

**Comment by wonder6oy** [comment]
Put this through a full day yesterday (thanks for the 1 block setting! - PERFECT!!)
Had one crash early on, but remarkably stable throughout the rest of the day.
Loving this app!

**Comment by norburybrook** [comment]
Congrats Andreas, Been using it all day without a single issue. 2 windows 10 machines with Cubase 11 Mainly AA plugins but a few virtual instruments and also Aether and B2 reverbs all on the salve machine 😃  Great stuff.  M Sent from Mail for Windows 10 From: wonder6oySent: 24 November 2020 17:30To: apohl79/audiogridderCc: SubscribedSubject: Re: [apohl79/audiogridder] v9 for the president:) (#228) Put this through a full day yesterday (thanks for the 1 block setting! - PERFECT!!)Had one crash early on, but remarkably stable throughout the rest of the day.Loving this app!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by simon1176f** [comment]
SO good! I was using Beta 4 but Beta 9 is really amazing. Well done mate.

**Comment by timbit2006** [comment]
Good to hear there's a new version and it's working out for those that used Beta 4 as that's what I'm still on. I think I may do the upgrade in three weeks from now though after the stress from the black friday madness and start of holiday season is over haha. I'll also be adding another machine to my setup which will host all of my SWAM Woodwinds so that will be a good time to switch.
