### ISSUE TITLE
SSL FX Plugins only show in up in instruments

### ISSUE THREAD

**Issue by gatd** [apohl79/audiogridder#317]
SSL FX Plugins only show in up as instruments and not audio fx as they should
beta 10.1.11 and its same in beta 10.1.10

**Comment by CaBuffalo** [comment]
Hey, Which plugin is it?

**Comment by gatd** [comment]
all the ssl ones and only the vst3 versions

**Comment by apohl79** [comment]
You can disable the server side filter in the plugin settings under plugin menu. You will see all plugins - no matter if instrument or fx.

AG is filtering plugins on the server side based on the channel config of the connecting AG plugin. Some plugins do not report their supported channels properly until they get really instantiated. 

Please follow the bug reporting (https://audiogridder.com/bug-reports) steps to provide the required info, if you have more problems. Also please open a "help" discussion thread instead of an issue. Thx!
