### ISSUE TITLE
New update ..Instruments sounds only in the time of session playing..!!

### ISSUE THREAD

**Issue by abysalvinthomas** [apohl79/audiogridder#498]
thank you for the new update ...especially Plugin sandboxing...wow...!!
but  i have facing a problem with cubase 10 pro
In plugin side ....all instruments are fine but its not sounding..( no sound)
its sounds only when curser moves....that menace..its sounds only in the time of session playing...(transport window play on)
what can i do...?

**Comment by apohl79** [comment]
This will be addressed in the next beta, see https://github.com/apohl79/audiogridder/discussions/495#discussioncomment-625127 and here for the commit https://github.com/apohl79/audiogridder/commit/c344c0048444c806a843cd930b203a82df146f48.

Please create discussion threads rather than issue tickets. Thx!
