### ISSUE TITLE
new Alpha 11 more slow response with Acustica plugin (Mac)

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#52]
hi, with this release some  acustica plugin ( pink4) have very very slow   response comand and also slow visual response with other  alpha 10release no
why? no that first are super speed but you can use it...
...with Mac

**Comment by apohl79** [comment]
and going back to 10 on the client and server machine solves the issue?

**Comment by thelux68** [comment]
mmm. no if now install 10 I see also vst2  I'm not able to downgrade to 10 so for now I not can use pink4  by Acustica Audio

**Comment by thelux68** [comment]
but more plugin that use vu meter by acustica are more slow,  equalizer  or compressor etc same plugin on cubase work  fine

**Comment by thelux68** [comment]
ok try

**Comment by thelux68** [comment]
Ok I tried on version 10 the compressor Id pink4  is more reactive while the equalizers are unusable with version 11 even the compressor cannot use it .

**Comment by apohl79** [comment]
Ok thx for the report. I will see if i can reproduce this and will investigate the problem.

**Comment by thelux68** [comment]
Ok you can try demo of pink4 By install aquarius 

Maurizio Altieri 
Cell: +39 3475416062
Tel:  +39 041 453431
maurizio.altieri@icloud.com 
Via Amatore Sciesa ,13
31021 Mogliano Veneto
Treviso
ITALY

**Comment by den0rk** [comment]
I've been testing Sand3 (also from Acustica Audio) with the latest alpha version, there were some spikes in latency, but it was manageable. The problem is that sometimes, for several seconds everything would freeze, and when it returned to work, some of the last adjustments made in the plugin had been lost. On the server you could see how the plugin disappeared from the screen and then returned

I think this application is highly anticipated for Acustica Audio users, due to the high CPU consumption of these plugins.

Please, if you need to test you can download the demos or some of their free products.

**Comment by thelux68** [comment]
Hi , i can confirm that disabling “screen difference detection” 
the controls react much better...some plugin more than other

**Comment by igbro** [comment]
I confirm this on Windows too.
Cubase 10.5.20 here I7 win7 / 2 x Xeon win7 server. 
4 Acustica plugins (VST2) with screen difference detection off, working like a charm!! (too sluggish with it on)
My server is almost idling!!!!  What is actually eating the more here is the GUI streaming!!!
I'm using VEP for VSTi but it's not suitable for FX routing wise.
Awesome job Abdreas!
