### ISSUE TITLE
Connection-Disconnection Loop with Mac OS server

### ISSUE THREAD

**Issue by apohl79** [apohl79/audiogridder#738]
### Discussed in https://github.com/apohl79/audiogridder/discussions/603

<div type='discussions-op-text'>

<sup>Originally posted by **Henri75** June  8, 2021</sup>
Hi,

First, audiogridder is an amazing work and a game changer ! You are doing an amazing work !

I have a real issue using it on Mac OS Cataline : when I open a new audiogridder plugin and try to connect to a server running MacOS Catalina It keeps connecting and disconnecting (led are bliking green and red). It happens on a new project, just by inserting audiogridder and try to connect the server. Logs from both sides show the issue.

I spend days trying everything : new ethernet adapter, cable, switch etc ... Everything is running with gigabit adapter and a 10Gbit  switch. The same computer running Windows in bootcamp works fine, so the issue seems to be with the Mac versions.

Sometimes I solved the problem by disabling the audiogridder insert and reneabling it and it may works. When I reload the same project same problems happens.

Attached are the logs, everything is up to date (OS etc ...) and running 1.2.0 beta 3.

By the way in the plugin monitor view it will be usefull to have  a summary of servers and CPU usage :) currently you need to open every plugin to have an idea of how it is...  Moreover (and I have no idea how easy it is ...) but I experienced some drops on large projec (with low cpu usage on server, and less than 10% bandwith on servers and client). In some case (not all) it seems to be related to CPU spikes on some core. So it may be usefull too to have some warnings or indicators on core usage/spkies (when some sandbox reach 100%/cpu) to detect such things and dispatch differently the plugins.

[AudiogridderLogs.zip](https://github.com/apohl79/audiogridder/files/6615213/AudiogridderLogs.zip)

I hope a bew beta will be there soon.

Thanks again for your AMAZING work :)</div>

**Comment by kngdroopz** [comment]
Hi people,

I think I'm having a similar experience as Henri75, I was using audiogridder in the early part of last year, I was able to incorporate audiogridder into any cubase session I had with little to no issues. I recently updated cubase and downloaded the latest version of audio gridder. I installed the server on my Macbook Pro and the plugin on my PC as I want to use my Mac as the slave computer as I did before and for some reason just opening the plugin on an audio track in my session causes all the audio to stop playing. I've tried different ethernet cables, Bata version of software and different DAWs and the result is the same. every time I insert audiogridder plugin on a channel with a signal the audiogridder plugin causes me to loose signal and playback. My CPU goes nuts each time I engage the audiogridder plugin and as soon as I bypass it I regain playback and sound. Not sure what's changed between the version i had and the version available not but it is now unusable due to these issues I've explained. I hope this helps the DevTeam to iron out these creases as I don't know how Ill be able to use my Apollo with my PC again

**Comment by kngdroopz** [comment]
Who is this? Do you have an answer for me?

**Comment by apohl79** [comment]
Try beta7. Your problem sounds like a latency issue. If you have multiple network interfaces, like wired and wireless, make sure you communicate via the wired interface. Try disabling wifi. Also check the statistics on the plugin and server side (do you see data coming through). The plugin monitor might reveal something too. Try higher buffer settings (I/O buffer in the DAW and AG blocks).

**Comment by kngdroopz** [comment]
Thanks, I'll check it out and get back to you by the end of the week

**Comment by kngdroopz** [comment]
Hi,
I can't find Beta7, I only see beat 8. I'll give it a try and let you know
what happens

**Comment by kngdroopz** [comment]
Hi Andreas
I looked for beta 7 but couldn't find it, can you send a link? to both the
mac and windows versions? I tried increasing the buffer to its maximum
capacity and the audio was still intermittent,  therefore not usable.
Any help would be appreciated.

Thanks
