### ISSUE TITLE
Crashes in alpha 16

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#82]
Audio engine crashes continue in alpha 16 in Studio One.
I think it happens during auto save.

**Comment by Paatjoo** [comment]
And sometimes, the server loses the connection in screen capture setting (osx)

**Comment by Paatjoo** [comment]
Here a crash report from the server app.


[crash beta 16 server.txt](https://github.com/apohl79/audiogridder/files/4819245/crash.beta.16.server.txt)

**Comment by Paatjoo** [comment]
The project I'm working on atm doesn't open plugins within AG anymore.
They stay greyed out (don't get yellow) and I can't edit anymore. Studio One doesn't crash, but AG doesn't work...

**Comment by apohl79** [comment]
nebula is crashing the AG server:

```
0   com.acusticaaudio.NUW         	0x00000001181d1f18 juce::XmlDocument::parseDTD() + 40\
1   com.acusticaaudio.NUW         	0x00000001181d1a07 juce::XmlDocument::parseDocumentElement(juce::CharPointer_UTF8, bool) + 71\
2   com.acusticaaudio.NUW         	0x00000001181d18e4 juce::XmlDocument::getDocumentElement(bool) + 436\
3   com.acusticaaudio.NUW         	0x000000011819da79 juce::getNebulaConfig(char*, char*, bool*) + 425\
4   com.acusticaaudio.NUW         	0x000000011819e8b5 GetPluginFactory + 181\
5   com.e47.AudioGridderServer    	0x0000000106719d6e juce::DLLHandle::getPluginFactory() + 110\
```

I can't see which XML config file nebula can't parse, but I suggest that you investigate in this direction.

> They stay greyed out (don't get yellow) and I can't edit anymore

This happens if the server fails to load the plugins or is not available (because of nebula crashing it I guess).

You will probably have to unload the AG plugin which crashes AG server and setup up the plugin chain from scratch.
